/**
 * API Module Index
 *
 * This file serves as a central module for exporting all API functions used in the web application.
 * It aggregates the API functions from different modules (auth, care, health, plan, gamification,
 * notifications, settings, and wellness) into a single location, making it easier to import and
 * use them throughout the application.
 */

// Authentication API functions
export {
    login,
    logout,
    getProfile,
    changePassword,
    enable2FA,
    disable2FA,
    configure2FA,
    deleteAccount,
    register,
    verifyMfa,
    refreshToken,
    socialLogin,
    forgotPassword,
    verifyEmail,
    setPassword,
    updateProfile,
    registerBiometricKey,
    getBiometricChallenge,
    verifyBiometricSignature,
    getActiveSessions,
    revokeSession,
} from './auth';
export type { SessionEntry } from './auth';

// Care Journey API functions
export {
    getAppointments,
    getAppointment,
    getProviders,
    bookAppointment,
    cancelAppointment,
    getAppointmentDetail,
    rescheduleAppointment,
    markNoShow,
    analyzeSymptoms,
    checkSymptoms,
    getConditions,
    getConditionDetail,
    saveSymptomReport,
    getSelfCareInstructions,
    getEmergencyInfo,
    getSymptomHistory,
    getSymptomVitals,
    uploadSymptomPhoto,
    createTelemedicineSession,
    getTelemedicineSession,
    joinTelemedicineSession,
    endTelemedicineSession,
    sendTelemedicineMessage,
    getWaitingRoom,
    getTelemedicineControls,
    searchProviders,
    getDoctorProfile,
    getDoctorReviews,
    getDoctorAvailability,
    getDoctorFilters,
    saveFavoriteDoctor,
    removeFavoriteDoctor,
    getSavedDoctors,
    getDoctorSearchList,
    getVisitSummary,
    getFollowUp,
    getVisitPrescriptions,
    getLabOrders,
    getReferral,
    getPreVisitChecklist,
    getBookingTypes,
    getBookingSchedule,
    confirmBooking,
    submitInsurance,
    uploadBookingDocuments,
    getPaymentSummary,
    getPaymentReceipt,
    getMedicalRecords,
    submitDoctorReview,
    getVisitHistory,
    getAppointmentReminders,
    updatePreVisitChecklist,
    getTelemedicineMessages,
    getProviderSpecialties,
    getProviderInsurances,
    getNearbyProviders,
    getUrgentCareLocations,
    getSecondOpinion,
} from './care';

// Health Journey API functions
export {
    getHealthMetrics,
    getHealthGoals,
    getMedicalHistory,
    getConnectedDevices,
    createHealthMetric,
    getSleepLogs,
    createSleepLog,
    getSleepQuality,
    getSleepDiary,
    getSleepTrends,
    getSleepGoals,
    getSleepDetail,
    getBedtimeRoutine,
    getSmartAlarm,
    getSleepInsights,
    syncSleepDevice,
    exportSleepData,
    getActivitySessions,
    createActivitySession,
    getActivityGoals,
    getActivityHistory,
    getActivityTrends,
    getActivityDetail,
    getWorkouts,
    getActivityChallenges,
    getActivityDeviceData,
    getActivityWeeklySummary,
    getNutritionLogs,
    createNutritionLog,
    getMealPlan,
    getRecipes,
    getNutrientAnalysis,
    getNutritionGoals,
    getNutritionHistory,
    searchFood,
    scanBarcode,
    getNutritionWeeklySummary,
    getCycleDays,
    logCycleDay,
    getCyclePredictions,
    getCycleSymptomLog,
    getCycleMoodLog,
    getCycleInsights,
    getCycleCalendar,
    getCycleReminders,
    updateCycleSettings,
    exportCycleData,
    getCycleHistory,
    getCycleDetail,
    logFlow,
    getFertilityWindow,
    shareCycleWithPartner,
    getWellnessArticles,
    getWellnessArticleDetail,
    getWellnessVideos,
    getWellnessPrograms,
    getWellnessBookmarks,
    addWellnessBookmark,
    removeWellnessBookmark,
    searchWellnessResources,
    submitAssessmentStep,
    getAssessmentResults,
    getHealthScore,
    getMedications,
    addMedication,
    editMedication,
    deleteMedication,
    logMedicationDose,
    logMissedDose,
    getMedicationSideEffects,
    reportSideEffect,
    getMedicationSchedule,
    getMedicationAlarms,
    getMedicationReminders,
    getHealthGoalsRest,
    createHealthGoal,
    updateHealthGoal,
    getHealthGoalProgress,
    updateSleepGoals,
    updateSmartAlarm,
    updateBedtimeRoutine,
    createSleepDiaryEntry,
    deleteSleepLog,
    createActivityGoal,
    updateActivityGoal,
    joinActivityChallenge,
    createWorkout,
    deleteActivitySession,
    deleteNutritionLog,
    updateNutritionGoals,
    createMealPlan,
    getRecipeDetail,
    getWaterIntake,
    updateCycleReminder,
    getCycleSettings,
    deleteHealthGoal,
    disconnectDevice,
    getDeviceSyncHistory,
} from './health';

// Plan Journey API functions
export {
    getPlan,
    getClaims,
    getCoverage,
    getBenefits,
    submitClaim,
    updateClaim,
    cancelClaim,
    uploadClaimDocument,
    simulateCost,
    getDigitalCard,
    getPlans,
    getClaim,
    getCoverageDetail,
    getClaimStatusTimeline,
    getClaimDocuments,
    getPlanDashboard,
    getNetworkProviders,
    getEOBs,
    getDeductibleStatus,
    getCopayInfo,
    getPreAuthStatus,
    downloadClaimDocument,
    getClaimAppeals,
    submitClaimAppeal,
    getPlanComparison,
    getDigitalCardShare,
    getCoverageSummary,
    requestPreAuth,
    getClaimEstimate,
    getPlanDocuments,
    exportClaimData,
    getPaymentHistory,
} from './plan';

// Gamification API functions
export {
    getGameProfile,
    getUserAchievements,
    getUserQuests,
    getUserRewards,
    getJourneyAchievements,
    acknowledgeAchievement,
    triggerGamificationEvent,
    updateGameProfile,
    getLeaderboard,
    updateQuestProgress,
    completeQuest,
    redeemReward,
    getRewardHistory,
    getStreakStatus,
    updateStreak,
    getAchievementDetail,
    getQuestDetail,
    getRewardDetail,
    getXpHistory,
    getLevelProgress,
    getJourneyQuests,
    acknowledgeReward,
    getAchievementProgress,
    getDailyChallenge,
    getWeeklyChallenge,
} from './gamification';

// Notification API functions
export {
    getNotifications,
    markNotificationAsRead,
    subscribeToNotifications,
    markAllAsRead,
    deleteNotification,
    getNotificationPreferences,
    updateNotificationPreferences,
    getNotificationCategories,
    getUnreadCount,
    registerPushToken,
    unregisterPushToken,
    getNotificationHistory,
    clearAllNotifications,
    getNotificationDetail,
    snoozeNotification,
    scheduleNotification,
    getNotificationStats,
    getNotificationTemplates,
} from './notifications';

// Settings API functions
export * from './settings';

// Wellness API functions
export * from './wellness';
