nodeLinker: node-modules
npmRegistryServer: "https://registry.yarnpkg.com"
checksumBehavior: update

packageExtensions:
  agora-rtc-sdk@*:
    dependencies:
      follow-redirects: "1.15.4"
      axios: "1.6.8"
  agora-rtc-sdk-ng@*:
    dependencies:
      follow-redirects: "1.15.4"
      axios: "1.6.8"
  "@sentry/nextjs@*":
    dependencies:
      "@babel/traverse": "7.23.2"
      webpack: "5.76.0"
