apiVersion: v1
kind: Service
metadata:
  name: plan-journey
  namespace: plan-journey
  labels:
    app: plan-journey
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: plan-journey
