apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 80
      targetPort: 3006
      protocol: TCP
      name: http