/**
 * Unified Route Constants for the AUSTA SuperApp
 * Single source of truth for all navigation routes across mobile and web platforms.
 * Mobile routes use React Navigation screen names. Web routes use Next.js page paths.
 * Organized by journey/domain with backward-compatible legacy re-exports.
 */

// -- Auth Routes --------------------------------------------------------------
export const AUTH_ROUTES = {
    AUTH_WELCOME: 'AuthWelcome',
    AUTH_ONBOARDING: 'AuthOnboarding',
    AUTH_WELCOME_CTA: 'AuthWelcomeCTA',
    AUTH_LOGIN: 'AuthLogin',
    AUTH_REGISTER: 'AuthRegister',
    AUTH_FORGOT_PASSWORD: 'AuthForgotPassword',
    AUTH_MFA: 'AuthMFA',
    AUTH_EMAIL_VERIFY: 'AuthEmailVerify',
    AUTH_SET_PASSWORD: 'AuthSetPassword',
    AUTH_SOCIAL: 'AuthSocial',
    AUTH_PERSONALIZATION_INTRO: 'AuthPersonalizationIntro',
    AUTH_GOAL_SELECTION: 'AuthGoalSelection',
    AUTH_ONBOARDING_CONFIRMATION: 'AuthOnboardingConfirmation',
    WEB_AUTH_WELCOME: '/auth/welcome',
    WEB_AUTH_ONBOARDING: '/auth/onboarding',
    WEB_AUTH_LOGIN: '/auth/login',
    WEB_AUTH_REGISTER: '/auth/register',
    WEB_AUTH_FORGOT_PASSWORD: '/auth/forgot-password',
    WEB_AUTH_MFA: '/auth/mfa',
    WEB_AUTH_EMAIL_VERIFY: '/auth/email-verify',
    WEB_AUTH_SET_PASSWORD: '/auth/set-password',
    WEB_AUTH_SOCIAL: '/auth/social-auth',
    WEB_AUTH_PERSONALIZATION_INTRO: '/auth/personalization-intro',
    WEB_AUTH_GOAL_SELECTION: '/auth/goal-selection',
    WEB_AUTH_ONBOARDING_CONFIRMATION: '/auth/onboarding-confirmation',
} as const;

// -- Profile Routes -----------------------------------------------------------
export const PROFILE_ROUTES = {
    PROFILE_SETUP: 'ProfileSetup',
    PROFILE_HEALTH: 'ProfileHealth',
    PROFILE_INSURANCE: 'ProfileInsurance',
    PROFILE_ADDRESS: 'ProfileAddress',
    PROFILE_DOCUMENTS: 'ProfileDocuments',
    PROFILE_PHOTO: 'ProfilePhoto',
    PROFILE_CONFIRMATION: 'ProfileConfirmation',
    PROFILE_EMERGENCY_CONTACT: 'ProfileEmergencyContact',
    PROFILE_NOTIFICATION_PREFS: 'ProfileNotificationPrefs',
    PROFILE_BIOMETRIC_SETUP: 'ProfileBiometricSetup',
    WEB_PROFILE: '/profile',
    WEB_PROFILE_SETUP: '/profile/setup',
    WEB_PROFILE_ADDRESS: '/profile/address',
    WEB_PROFILE_DOCUMENTS: '/profile/documents',
    WEB_PROFILE_PHOTO: '/profile/photo',
    WEB_PROFILE_CONFIRMATION: '/profile/confirmation',
    WEB_PROFILE_EMERGENCY_CONTACT: '/profile/emergency-contact',
    WEB_PROFILE_NOTIFICATION_PREFS: '/profile/notification-prefs',
    WEB_PROFILE_BIOMETRIC_SETUP: '/profile/biometric-setup',
    WEB_PROFILE_SETTINGS: '/profile/settings',
    WEB_PROFILE_EDIT: '/profile/edit',
    WEB_PROFILE_NOTIFICATIONS: '/profile/notifications',
    WEB_PROFILE_PRIVACY: '/profile/privacy',
} as const;

// -- Home Routes --------------------------------------------------------------
export const HOME_ROUTES = {
    HOME: 'Home',
    HOME_METRICS: 'HomeMetrics',
    HOME_ALERT: 'HomeAlert',
    HOME_HEADER: 'HomeHeader',
    HOME_WEEKLY_SUMMARY: 'HomeWeeklySummary',
    HOME_BOTTOM_SHEET: 'HomeBottomSheet',
    HOME_MEDICATION_REMINDERS: 'HomeMedicationReminders',
    HOME_APPOINTMENT_WIDGET: 'HomeAppointmentWidget',
    HOME_HEALTH_TIPS: 'HomeHealthTips',
    HOME_EMPTY: 'HomeEmpty',
    WEB_HOME: '/home',
    WEB_HOME_METRICS: '/home/metrics',
    WEB_HOME_ALERT: '/home/alert',
    WEB_HOME_WEEKLY_SUMMARY: '/home/weekly-summary',
    WEB_HOME_BOTTOM_SHEET: '/home/bottom-sheet',
    WEB_HOME_MEDICATION_REMINDERS: '/home/medication-reminders',
    WEB_HOME_APPOINTMENT_WIDGET: '/home/appointment-widget',
    WEB_HOME_HEALTH_TIPS: '/home/health-tips',
    WEB_HOME_EMPTY: '/home/empty',
} as const;

// -- Health Journey Routes (Green) --------------------------------------------
export const HEALTH_ROUTES = {
    // Mobile — core
    HEALTH_DASHBOARD: 'HealthDashboard',
    HEALTH_MEDICAL_HISTORY: 'HealthMedicalHistory',
    HEALTH_HEALTH_GOALS: 'HealthGoals',
    HEALTH_DEVICE_CONNECTION: 'HealthDeviceConnection',
    HEALTH_METRIC_DETAIL: 'HealthMetricDetail',
    HEALTH_ADD_METRIC: 'HealthAddMetric',
    HEALTH_ASSESSMENT_WIZARD: 'HealthAssessmentWizard',
    // Mobile — medication
    HEALTH_MEDICATION_LIST: 'HealthMedicationList',
    HEALTH_MEDICATION_ADD: 'HealthMedicationAdd',
    HEALTH_MEDICATION_DETAIL: 'HealthMedicationDetail',
    HEALTH_MEDICATION_SEARCH: 'HealthMedicationSearch',
    HEALTH_MEDICATION_REMINDER: 'HealthMedicationReminder',
    HEALTH_MEDICATION_ALARM: 'HealthMedicationAlarm',
    HEALTH_MEDICATION_CALENDAR: 'HealthMedicationCalendar',
    HEALTH_MEDICATION_EMPTY: 'HealthMedicationEmpty',
    HEALTH_MEDICATION_ADD_CONFIRMATION: 'HealthMedicationAddConfirmation',
    HEALTH_MEDICATION_DOSE_TAKEN: 'HealthMedicationDoseTaken',
    HEALTH_MEDICATION_DOSE_MISSED: 'HealthMedicationDoseMissed',
    HEALTH_MEDICATION_EDIT: 'HealthMedicationEdit',
    HEALTH_MEDICATION_DELETE_CONFIRM: 'HealthMedicationDeleteConfirm',
    HEALTH_MEDICATION_ADHERENCE: 'HealthMedicationAdherence',
    HEALTH_MEDICATION_MONTHLY_REPORT: 'HealthMedicationMonthlyReport',
    HEALTH_MEDICATION_REFILL_REMINDER: 'HealthMedicationRefillReminder',
    HEALTH_MEDICATION_DRUG_INTERACTION: 'HealthMedicationDrugInteraction',
    HEALTH_MEDICATION_SIDE_EFFECTS_LOG: 'HealthMedicationSideEffectsLog',
    HEALTH_MEDICATION_SIDE_EFFECT_FORM: 'HealthMedicationSideEffectForm',
    HEALTH_MEDICATION_PHARMACY_LOCATOR: 'HealthMedicationPharmacyLocator',
    HEALTH_MEDICATION_PRESCRIPTION_PHOTO: 'HealthMedicationPrescriptionPhoto',
    HEALTH_MEDICATION_OCR_REVIEW: 'HealthMedicationOCRReview',
    HEALTH_MEDICATION_SHARE_CAREGIVER: 'HealthMedicationShareCaregiver',
    HEALTH_MEDICATION_CAREGIVER_ACCESS: 'HealthMedicationCaregiverAccess',
    HEALTH_MEDICATION_EXPORT: 'HealthMedicationExport',
    // Mobile — cycle tracking (Module 12)
    HEALTH_CYCLE_HOME: 'HealthCycleHome',
    HEALTH_CYCLE_CALENDAR: 'HealthCycleCalendar',
    HEALTH_CYCLE_LOG_PERIOD: 'HealthCycleLogPeriod',
    HEALTH_CYCLE_LOG_SYMPTOMS: 'HealthCycleLogSymptoms',
    HEALTH_CYCLE_LOG_FLOW: 'HealthCycleLogFlow',
    HEALTH_CYCLE_FERTILITY: 'HealthCycleFertility',
    HEALTH_CYCLE_PMS: 'HealthCyclePMS',
    HEALTH_CYCLE_HISTORY: 'HealthCycleHistory',
    HEALTH_CYCLE_ANALYSIS: 'HealthCycleAnalysis',
    HEALTH_CYCLE_INSIGHTS: 'HealthCycleInsights',
    HEALTH_CYCLE_ARTICLE_DETAIL: 'HealthCycleArticleDetail',
    HEALTH_CYCLE_REMINDERS: 'HealthCycleReminders',
    HEALTH_CYCLE_PARTNER_SHARING: 'HealthCyclePartnerSharing',
    HEALTH_CYCLE_SETTINGS: 'HealthCycleSettings',
    HEALTH_CYCLE_EXPORT: 'HealthCycleExportReport',
    // Web — core
    WEB_HEALTH: '/health',
    WEB_HEALTH_DASHBOARD: '/health/dashboard',
    WEB_HEALTH_HISTORY: '/health/history',
    WEB_HEALTH_GOALS: '/health/goals',
    WEB_HEALTH_DEVICES: '/health/devices',
    WEB_HEALTH_METRICS_DETAIL: '/health/metrics/:id',
    WEB_HEALTH_ASSESSMENT: '/health/assessment',
    // Web — medications
    WEB_HEALTH_MEDICATIONS: '/health/medications',
    WEB_HEALTH_MEDICATION_ADD: '/health/medications/add',
    WEB_HEALTH_MEDICATION_DETAIL: '/health/medications/:id',
    WEB_HEALTH_MEDICATION_REMINDER: '/health/medications/reminder',
    WEB_HEALTH_MEDICATION_SEARCH: '/health/medications/search',
    WEB_HEALTH_MEDICATION_ALARM: '/health/medications/alarm',
    WEB_HEALTH_MEDICATION_CALENDAR: '/health/medications/calendar',
    WEB_HEALTH_MEDICATION_EMPTY: '/health/medications/empty',
    WEB_HEALTH_MEDICATION_ADD_CONFIRMATION: '/health/medications/add-confirmation',
    WEB_HEALTH_MEDICATION_DOSE_TAKEN: '/health/medications/dose-taken',
    WEB_HEALTH_MEDICATION_DOSE_MISSED: '/health/medications/dose-missed',
    WEB_HEALTH_MEDICATION_EDIT: '/health/medications/edit',
    WEB_HEALTH_MEDICATION_DELETE_CONFIRM: '/health/medications/delete-confirm',
    WEB_HEALTH_MEDICATION_ADHERENCE: '/health/medications/adherence',
    WEB_HEALTH_MEDICATION_MONTHLY_REPORT: '/health/medications/monthly-report',
    WEB_HEALTH_MEDICATION_REFILL_REMINDER: '/health/medications/refill-reminder',
    WEB_HEALTH_MEDICATION_DRUG_INTERACTION: '/health/medications/drug-interaction',
    WEB_HEALTH_MEDICATION_SIDE_EFFECTS: '/health/medications/side-effects',
    WEB_HEALTH_MEDICATION_SIDE_EFFECT_FORM: '/health/medications/side-effect-form',
    WEB_HEALTH_MEDICATION_PHARMACY_LOCATOR: '/health/medications/pharmacy-locator',
    WEB_HEALTH_MEDICATION_PRESCRIPTION_PHOTO: '/health/medications/prescription-photo',
    WEB_HEALTH_MEDICATION_OCR_REVIEW: '/health/medications/ocr-review',
    WEB_HEALTH_MEDICATION_SHARE_CAREGIVER: '/health/medications/share-caregiver',
    WEB_HEALTH_MEDICATION_CAREGIVER_ACCESS: '/health/medications/caregiver-access',
    WEB_HEALTH_MEDICATION_EXPORT: '/health/medications/export',
    // Web — cycle tracking (Module 12)
    WEB_HEALTH_CYCLE: '/health/cycle',
    WEB_HEALTH_CYCLE_TODAY: '/health/cycle/today',
    WEB_HEALTH_CYCLE_LOG_PERIOD: '/health/cycle/log-period',
    WEB_HEALTH_CYCLE_LOG_SYMPTOMS: '/health/cycle/log-symptoms',
    WEB_HEALTH_CYCLE_LOG_FLOW: '/health/cycle/log-flow',
    WEB_HEALTH_CYCLE_FERTILITY: '/health/cycle/fertility',
    WEB_HEALTH_CYCLE_PMS: '/health/cycle/pms-predictions',
    WEB_HEALTH_CYCLE_HISTORY: '/health/cycle/history',
    WEB_HEALTH_CYCLE_ANALYSIS: '/health/cycle/analysis',
    WEB_HEALTH_CYCLE_INSIGHTS: '/health/cycle/insights',
    WEB_HEALTH_CYCLE_ARTICLE: '/health/cycle/article',
    WEB_HEALTH_CYCLE_REMINDERS: '/health/cycle/reminders',
    WEB_HEALTH_CYCLE_PARTNER: '/health/cycle/partner-sharing',
    WEB_HEALTH_CYCLE_SETTINGS: '/health/cycle/settings',
    WEB_HEALTH_CYCLE_EXPORT: '/health/cycle/export',
} as const;

// -- Care Journey Routes (Orange) ---------------------------------------------
export const CARE_ROUTES = {
    // Mobile — core
    CARE_DASHBOARD: 'CareDashboard',
    CARE_APPOINTMENTS: 'CareAppointments',
    CARE_APPOINTMENT_BOOKING: 'CareAppointmentBooking',
    CARE_TELEMEDICINE: 'CareTelemedicine',
    CARE_MEDICATION_TRACKING: 'CareMedicationTracking',
    // Mobile — symptom checker
    CARE_SYMPTOM_CHECKER: 'CareSymptomChecker',
    CARE_SYMPTOM_BODY_MAP: 'CareSymptomBodyMap',
    CARE_SYMPTOM_DETAIL: 'CareSymptomDetail',
    CARE_SYMPTOM_SEVERITY: 'CareSymptomSeverity',
    CARE_SYMPTOM_QUESTIONS: 'CareSymptomQuestions',
    CARE_SYMPTOM_RESULT: 'CareSymptomResult',
    CARE_SYMPTOM_RECOMMENDATION: 'CareSymptomRecommendation',
    CARE_SYMPTOM_BODY_MAP_BACK: 'CareSymptomBodyMapBack',
    CARE_SYMPTOM_HEAD_DETAIL: 'CareSymptomHeadDetail',
    CARE_SYMPTOM_PHOTO_UPLOAD: 'CareSymptomPhotoUpload',
    CARE_SYMPTOM_MEDICAL_HISTORY: 'CareSymptomMedicalHistory',
    CARE_SYMPTOM_MEDICATION_CONTEXT: 'CareSymptomMedicationContext',
    CARE_SYMPTOM_VITALS: 'CareSymptomVitals',
    CARE_SYMPTOM_ANALYZING: 'CareSymptomAnalyzing',
    CARE_SYMPTOM_CONDITIONS_LIST: 'CareSymptomConditionsList',
    CARE_SYMPTOM_CONDITION_DETAIL: 'CareSymptomConditionDetail',
    CARE_SYMPTOM_SELF_CARE: 'CareSymptomSelfCare',
    CARE_SYMPTOM_EMERGENCY_WARNING: 'CareSymptomEmergencyWarning',
    CARE_SYMPTOM_BOOK_APPOINTMENT: 'CareSymptomBookAppointment',
    CARE_SYMPTOM_ER_LOCATOR: 'CareSymptomERLocator',
    CARE_SYMPTOM_SAVE_REPORT: 'CareSymptomSaveReport',
    CARE_SYMPTOM_SHARE_REPORT: 'CareSymptomShareReport',
    CARE_SYMPTOM_HISTORY: 'CareSymptomHistory',
    CARE_SYMPTOM_HISTORY_DETAIL: 'CareSymptomHistoryDetail',
    CARE_SYMPTOM_ACCURACY_RATING: 'CareSymptomAccuracyRating',
    CARE_SYMPTOM_FOLLOW_UP: 'CareSymptomFollowUp',
    CARE_SYMPTOM_DIARY: 'CareSymptomDiary',
    CARE_SYMPTOM_COMPARISON: 'CareSymptomComparison',
    // Mobile — consultation
    CARE_DOCTOR_SEARCH: 'CareDoctorSearch',
    CARE_DOCTOR_FILTERS: 'CareDoctorFilters',
    CARE_DOCTOR_PROFILE: 'CareDoctorProfile',
    CARE_DOCTOR_AVAILABILITY: 'CareDoctorAvailability',
    CARE_BOOKING_SCHEDULE: 'CareBookingSchedule',
    CARE_BOOKING_CONFIRMATION: 'CareBookingConfirmation',
    CARE_WAITING_ROOM: 'CareWaitingRoom',
    CARE_DOCTOR_REVIEWS: 'CareDoctorReviews',
    CARE_APPOINTMENT_TYPE: 'CareAppointmentType',
    CARE_BOOKING_REASON: 'CareBookingReason',
    CARE_BOOKING_DOCUMENTS: 'CareBookingDocuments',
    CARE_BOOKING_INSURANCE: 'CareBookingInsurance',
    CARE_BOOKING_SUCCESS: 'CareBookingSuccess',
    CARE_APPOINTMENTS_LIST: 'CareAppointmentsList',
    CARE_APPOINTMENT_RESCHEDULE: 'CareAppointmentReschedule',
    CARE_APPOINTMENT_CANCEL: 'CareAppointmentCancel',
    CARE_APPOINTMENT_CANCELLED: 'CareAppointmentCancelled',
    CARE_APPOINTMENT_NO_SHOW: 'CareAppointmentNoShow',
    CARE_PRE_VISIT_CHECKLIST: 'CarePreVisitChecklist',
    CARE_RATE_VISIT: 'CareRateVisit',
    CARE_SAVED_DOCTORS: 'CareSavedDoctors',
    // Mobile — telemedicine deep
    CARE_TELEMEDICINE_CONNECTING: 'CareTelemedicineConnecting',
    CARE_TELEMEDICINE_CONTROLS: 'CareTelemedicineControls',
    CARE_TELEMEDICINE_CHAT: 'CareTelemedicineChat',
    CARE_TELEMEDICINE_SCREEN_SHARE: 'CareTelemedicineScreenShare',
    CARE_TELEMEDICINE_END: 'CareTelemedicineEnd',
    // Mobile — post-visit + payment + records
    CARE_VISIT_SUMMARY: 'CareVisitSummary',
    CARE_VISIT_PRESCRIPTIONS: 'CareVisitPrescriptions',
    CARE_VISIT_FOLLOW_UP: 'CareVisitFollowUp',
    CARE_VISIT_LAB_ORDERS: 'CareVisitLabOrders',
    CARE_VISIT_REFERRAL: 'CareVisitReferral',
    CARE_PAYMENT_SUMMARY: 'CarePaymentSummary',
    CARE_PAYMENT_RECEIPT: 'CarePaymentReceipt',
    CARE_ASYNC_DOCTOR_CHAT: 'CareAsyncDoctorChat',
    CARE_MEDICAL_RECORDS: 'CareMedicalRecords',
    // Web — core
    WEB_CARE: '/care',
    WEB_CARE_APPOINTMENTS: '/care/appointments',
    WEB_CARE_APPOINTMENT_DETAIL: '/care/appointments/:id',
    WEB_CARE_APPOINTMENT_BOOK: '/care/appointments/book',
    WEB_CARE_TELEMEDICINE: '/care/telemedicine',
    WEB_CARE_TELEMEDICINE_SESSION: '/care/telemedicine/:id',
    WEB_CARE_TREATMENT_PLANS: '/care/treatment-plans',
    // Web — symptom checker
    WEB_CARE_SYMPTOM_CHECKER: '/care/symptom-checker',
    WEB_CARE_SYMPTOM_BODY_MAP: '/care/symptom-checker/body-map',
    WEB_CARE_SYMPTOM_DETAIL: '/care/symptom-checker/detail',
    WEB_CARE_SYMPTOM_SEVERITY: '/care/symptom-checker/severity',
    WEB_CARE_SYMPTOM_QUESTIONS: '/care/symptom-checker/questions',
    WEB_CARE_SYMPTOM_RESULT: '/care/symptom-checker/result',
    WEB_CARE_SYMPTOM_RECOMMENDATION: '/care/symptom-checker/recommendation',
    WEB_CARE_SYMPTOM_BACK_BODY_MAP: '/care/symptom-checker/back-body-map',
    WEB_CARE_SYMPTOM_HEAD_DETAIL: '/care/symptom-checker/head-detail',
    WEB_CARE_SYMPTOM_PHOTO_UPLOAD: '/care/symptom-checker/photo-upload',
    WEB_CARE_SYMPTOM_MEDICAL_HISTORY: '/care/symptom-checker/medical-history',
    WEB_CARE_SYMPTOM_MEDICATION_CONTEXT: '/care/symptom-checker/medication-context',
    WEB_CARE_SYMPTOM_VITALS: '/care/symptom-checker/vitals',
    WEB_CARE_SYMPTOM_ANALYZING: '/care/symptom-checker/analyzing',
    WEB_CARE_SYMPTOM_CONDITIONS_LIST: '/care/symptom-checker/conditions-list',
    WEB_CARE_SYMPTOM_CONDITION_DETAIL: '/care/symptom-checker/condition-detail',
    WEB_CARE_SYMPTOM_SELF_CARE: '/care/symptom-checker/self-care',
    WEB_CARE_SYMPTOM_EMERGENCY_WARNING: '/care/symptom-checker/emergency-warning',
    WEB_CARE_SYMPTOM_BOOK_APPOINTMENT: '/care/symptom-checker/book-appointment',
    WEB_CARE_SYMPTOM_ER_LOCATOR: '/care/symptom-checker/er-locator',
    WEB_CARE_SYMPTOM_SAVE_REPORT: '/care/symptom-checker/save-report',
    WEB_CARE_SYMPTOM_SHARE_REPORT: '/care/symptom-checker/share-report',
    WEB_CARE_SYMPTOM_HISTORY: '/care/symptom-checker/history',
    WEB_CARE_SYMPTOM_HISTORY_DETAIL: '/care/symptom-checker/history-detail',
    WEB_CARE_SYMPTOM_ACCURACY_RATING: '/care/symptom-checker/accuracy-rating',
    WEB_CARE_SYMPTOM_FOLLOW_UP: '/care/symptom-checker/follow-up',
    WEB_CARE_SYMPTOM_DIARY: '/care/symptom-checker/diary',
    WEB_CARE_SYMPTOM_COMPARISON: '/care/symptom-checker/comparison',
    // Web — consultation
    WEB_CARE_DOCTOR_SEARCH: '/care/appointments/search',
    WEB_CARE_DOCTOR_FILTERS: '/care/appointments/filters',
    WEB_CARE_DOCTOR_PROFILE: '/care/appointments/doctor/:id',
    WEB_CARE_DOCTOR_AVAILABILITY: '/care/appointments/doctor/availability',
    WEB_CARE_BOOKING_CONFIRMATION: '/care/appointments/confirm',
    WEB_CARE_WAITING_ROOM: '/care/appointments/waiting-room',
    WEB_CARE_DOCTOR_REVIEWS: '/care/appointments/reviews',
    WEB_CARE_APPOINTMENT_TYPE: '/care/appointments/appointment-type',
    WEB_CARE_BOOKING_REASON: '/care/appointments/reason-for-visit',
    WEB_CARE_BOOKING_DOCUMENTS: '/care/appointments/documents',
    WEB_CARE_BOOKING_INSURANCE: '/care/appointments/insurance',
    WEB_CARE_BOOKING_SUCCESS: '/care/appointments/success',
    WEB_CARE_APPOINTMENTS_LIST: '/care/appointments/list',
    WEB_CARE_APPOINTMENT_RESCHEDULE: '/care/appointments/reschedule',
    WEB_CARE_APPOINTMENT_CANCEL: '/care/appointments/cancel',
    WEB_CARE_APPOINTMENT_CANCELLED: '/care/appointments/cancelled',
    WEB_CARE_APPOINTMENT_NO_SHOW: '/care/appointments/no-show',
    WEB_CARE_PRE_VISIT_CHECKLIST: '/care/appointments/pre-visit',
    WEB_CARE_RATE_VISIT: '/care/appointments/rate-visit',
    WEB_CARE_SAVED_DOCTORS: '/care/appointments/saved-doctors',
    // Web — telemedicine deep
    WEB_CARE_TELEMEDICINE_CONNECTING: '/care/telemedicine/connecting',
    WEB_CARE_TELEMEDICINE_CONTROLS: '/care/telemedicine/controls',
    WEB_CARE_TELEMEDICINE_CHAT: '/care/telemedicine/chat',
    WEB_CARE_TELEMEDICINE_SCREEN_SHARE: '/care/telemedicine/screen-share',
    WEB_CARE_TELEMEDICINE_END: '/care/telemedicine/end',
    // Web — post-visit + payment + records
    WEB_CARE_VISIT_SUMMARY: '/care/visits/summary',
    WEB_CARE_VISIT_PRESCRIPTIONS: '/care/visits/prescriptions',
    WEB_CARE_VISIT_FOLLOW_UP: '/care/visits/follow-up',
    WEB_CARE_VISIT_LAB_ORDERS: '/care/visits/lab-orders',
    WEB_CARE_VISIT_REFERRAL: '/care/visits/referral',
    WEB_CARE_PAYMENT_SUMMARY: '/care/payments/summary',
    WEB_CARE_PAYMENT_RECEIPT: '/care/payments/receipt',
    WEB_CARE_ASYNC_CHAT: '/care/async-chat',
    WEB_CARE_MEDICAL_RECORDS: '/care/medical-records',
} as const;

// -- Plan & Benefits Journey Routes (Blue) ------------------------------------
export const PLAN_ROUTES = {
    PLAN_DASHBOARD: 'PlanDashboard',
    PLAN_COVERAGE: 'PlanCoverage',
    PLAN_DIGITAL_CARD: 'PlanDigitalCard',
    PLAN_CLAIMS: 'PlanClaims',
    PLAN_COST_SIMULATOR: 'PlanCostSimulator',
    WEB_PLAN: '/plan',
    WEB_PLAN_BENEFITS: '/plan/benefits',
    WEB_PLAN_COVERAGE: '/plan/coverage',
    WEB_PLAN_CLAIMS: '/plan/claims',
    WEB_PLAN_CLAIMS_SUBMIT: '/plan/claims/submit',
    WEB_PLAN_CLAIMS_DETAIL: '/plan/claims/:id',
    WEB_PLAN_SIMULATOR: '/plan/simulator',
    WEB_PLAN_CARD: '/plan/card',
} as const;

// -- Gamification Journey Routes (Purple) -------------------------------------
export const GAMIFICATION_ROUTES = {
    GAMIFICATION_ACHIEVEMENTS: 'GamificationAchievements',
    GAMIFICATION_DETAIL: 'GamificationAchievementDetail',
    GAMIFICATION_LEADERBOARD: 'GamificationLeaderboard',
    GAMIFICATION_QUESTS: 'GamificationQuests',
    GAMIFICATION_QUEST_DETAIL: 'GamificationQuestDetail',
    GAMIFICATION_REWARDS: 'GamificationRewards',
    GAMIFICATION_REWARD_DETAIL: 'GamificationRewardDetail',
    WEB_ACHIEVEMENTS: '/achievements',
    WEB_ACHIEVEMENT_DETAIL: '/achievements/:id',
    WEB_LEADERBOARD: '/achievements/leaderboard',
    WEB_QUESTS: '/achievements/quests',
    WEB_QUEST_DETAIL: '/achievements/quests/:id',
    WEB_REWARDS: '/achievements/rewards',
    WEB_REWARD_DETAIL: '/achievements/rewards/:id',
} as const;

// -- Settings Routes ----------------------------------------------------------
export const SETTINGS_ROUTES = {
    SETTINGS_PERSONAL_INFO: 'SettingsPersonalInfo',
    SETTINGS_CHANGE_PASSWORD: 'SettingsChangePassword',
    SETTINGS_TWO_FACTOR: 'SettingsTwoFactor',
    SETTINGS_BIOMETRIC: 'SettingsBiometric',
    SETTINGS_DATA_EXPORT: 'SettingsDataExport',
    SETTINGS_DELETE_ACCOUNT: 'SettingsDeleteAccount',
    SETTINGS_DELETE_CONFIRM: 'SettingsDeleteConfirm',
    SETTINGS_LANGUAGE: 'SettingsLanguage',
    SETTINGS_THEME: 'SettingsTheme',
    SETTINGS_ACCESSIBILITY: 'SettingsAccessibility',
    SETTINGS_CONNECTED_DEVICES: 'SettingsConnectedDevices',
    SETTINGS_HEALTH_PLAN: 'SettingsHealthPlan',
    SETTINGS_INSURANCE_DOCS: 'SettingsInsuranceDocs',
    SETTINGS_DEPENDENTS: 'SettingsDependents',
    SETTINGS_ADD_DEPENDENT: 'SettingsAddDependent',
    SETTINGS_EMERGENCY_CONTACTS: 'SettingsEmergencyContacts',
    SETTINGS_ADDRESSES: 'SettingsAddresses',
    SETTINGS_ADD_ADDRESS: 'SettingsAddAddress',
    SETTINGS_TERMS: 'SettingsTerms',
    SETTINGS_PRIVACY_POLICY: 'SettingsPrivacyPolicy',
    SETTINGS_ABOUT: 'SettingsAbout',
    SETTINGS_LOGOUT: 'SettingsLogout',
    SETTINGS_FEEDBACK: 'SettingsFeedback',
    WEB_SETTINGS_PERSONAL_INFO: '/settings/personal-info',
    WEB_SETTINGS_CHANGE_PASSWORD: '/settings/change-password',
    WEB_SETTINGS_TWO_FACTOR: '/settings/two-factor',
    WEB_SETTINGS_BIOMETRIC: '/settings/biometric',
    WEB_SETTINGS_DATA_EXPORT: '/settings/data-export',
    WEB_SETTINGS_DELETE_ACCOUNT: '/settings/delete-account',
    WEB_SETTINGS_DELETE_CONFIRM: '/settings/delete-confirm',
    WEB_SETTINGS_LANGUAGE: '/settings/language',
    WEB_SETTINGS_THEME: '/settings/theme',
    WEB_SETTINGS_ACCESSIBILITY: '/settings/accessibility',
    WEB_SETTINGS_CONNECTED_DEVICES: '/settings/connected-devices',
    WEB_SETTINGS_HEALTH_PLAN: '/settings/health-plan',
    WEB_SETTINGS_INSURANCE_DOCS: '/settings/insurance-docs',
    WEB_SETTINGS_DEPENDENTS: '/settings/dependents',
    WEB_SETTINGS_ADD_DEPENDENT: '/settings/add-dependent',
    WEB_SETTINGS_EMERGENCY_CONTACTS: '/settings/emergency-contacts',
    WEB_SETTINGS_ADDRESSES: '/settings/addresses',
    WEB_SETTINGS_ADD_ADDRESS: '/settings/add-address',
    WEB_SETTINGS_FEEDBACK: '/settings/feedback',
    WEB_SETTINGS_LOGOUT: '/settings/logout',
} as const;

// -- Help Center Routes -------------------------------------------------------
export const HELP_ROUTES = {
    HELP_HOME: 'HelpHome',
    HELP_FAQ_CATEGORY: 'HelpFAQCategory',
    HELP_FAQ_DETAIL: 'HelpFAQDetail',
    HELP_CONTACT: 'HelpContact',
    HELP_CHAT: 'HelpChat',
    HELP_REPORT: 'HelpReport',
    WEB_HELP: '/help',
    WEB_HELP_FAQ: '/help/faq',
    WEB_HELP_FAQ_DETAIL: '/help/faq/:id',
    WEB_HELP_FAQ_CATEGORY: '/help/faq-category',
    WEB_HELP_FAQ_DETAIL_LEGACY: '/help/faq-detail',
    WEB_HELP_CONTACT: '/help/contact',
    WEB_HELP_CHAT: '/help/chat',
    WEB_HELP_REPORT: '/help/report',
    WEB_HELP_TERMS: '/help/terms',
    WEB_HELP_PRIVACY: '/help/privacy',
    WEB_HELP_ABOUT: '/help/about',
} as const;

// -- Global / Cross-Journey Routes --------------------------------------------
export const GLOBAL_ROUTES = {
    NOTIFICATIONS: 'Notifications',
    NOTIFICATION_DETAIL: 'NotificationDetail',
    NOTIFICATION_UNREAD: 'NotificationUnread',
    NOTIFICATION_CATEGORY_FILTER: 'NotificationCategoryFilter',
    NOTIFICATION_EMPTY: 'NotificationEmpty',
    NOTIFICATION_SETTINGS: 'NotificationSettings',
    PROFILE: 'Profile',
    SETTINGS: 'Settings',
    ACHIEVEMENTS: 'Achievements',
    SEARCH: 'Search',
    SEARCH_RESULTS: 'SearchResults',
    SEARCH_DOCTOR_RESULTS: 'SearchDoctorResults',
    SEARCH_ARTICLE_RESULTS: 'SearchArticleResults',
    SEARCH_MEDICATION_RESULTS: 'SearchMedicationResults',
    SEARCH_NO_RESULTS: 'SearchNoResults',
    SETTINGS_EDIT: 'SettingsEdit',
    SETTINGS_NOTIFICATIONS: 'SettingsNotifications',
    SETTINGS_PRIVACY: 'SettingsPrivacy',
    WEB_NOTIFICATIONS: '/notifications',
    WEB_NOTIFICATION_DETAIL: '/notifications/detail',
    WEB_NOTIFICATION_UNREAD: '/notifications/unread',
    WEB_NOTIFICATION_CATEGORY_FILTER: '/notifications/category-filter',
    WEB_NOTIFICATION_EMPTY: '/notifications/empty',
    WEB_NOTIFICATION_SETTINGS: '/notifications/settings',
    WEB_SEARCH: '/search',
    WEB_SEARCH_RESULTS: '/search/results',
    WEB_SEARCH_DOCTOR_RESULTS: '/search/doctor-results',
    WEB_SEARCH_ARTICLE_RESULTS: '/search/article-results',
    WEB_SEARCH_MEDICATION_RESULTS: '/search/medication-results',
    WEB_SEARCH_NO_RESULTS: '/search/no-results',
    WEB_SETTINGS_EDIT: '/profile/edit',
    WEB_SETTINGS_NOTIFICATIONS: '/profile/notifications',
    WEB_SETTINGS_PRIVACY: '/profile/privacy',
} as const;

// -- Error Routes (programmatic, not in navigator) ----------------------------
export const ERROR_ROUTES = {
    ERROR_NO_INTERNET: 'ErrorNoInternet',
    ERROR_SERVER: 'ErrorServer',
    ERROR_MAINTENANCE: 'ErrorMaintenance',
    ERROR_FORCE_UPDATE: 'ErrorForceUpdate',
    WEB_ERROR_NO_INTERNET: '/error/no-internet',
    WEB_ERROR_SERVER: '/error/server-error',
    WEB_ERROR_MAINTENANCE: '/error/maintenance',
    WEB_ERROR_FORCE_UPDATE: '/error/force-update',
} as const;

// -- Flat ROUTES object (backward compat with mobile routes.ts) ---------------
export const ROUTES = {
    ...HOME_ROUTES,
    ...AUTH_ROUTES,
    ...PROFILE_ROUTES,
    ...HEALTH_ROUTES,
    ...CARE_ROUTES,
    ...PLAN_ROUTES,
    ...GAMIFICATION_ROUTES,
    ...SETTINGS_ROUTES,
    ...HELP_ROUTES,
    ...GLOBAL_ROUTES,
    ...ERROR_ROUTES,
} as const;

// -- Legacy re-exports (deprecated, values match original shared/constants/routes.ts) --
/** @deprecated Use AUTH_ROUTES */ export const MOBILE_AUTH_ROUTES = {
    WELCOME: 'WelcomeSplash',
    ONBOARDING: 'Onboarding',
    WELCOME_CTA: 'WelcomeCTA',
    LOGIN: 'Login',
    REGISTER: 'Register',
    FORGOT_PASSWORD: 'ForgotPassword',
    MFA: 'MFA',
    EMAIL_VERIFY: 'EmailVerify',
    SET_PASSWORD: 'SetPassword',
} as const;
/** @deprecated Use PROFILE_ROUTES */ export const MOBILE_PROFILE_ROUTES = {
    SETUP: 'ProfileSetup',
    HEALTH: 'ProfileHealth',
    INSURANCE: 'ProfileInsurance',
    ADDRESS: 'ProfileAddress',
    DOCUMENTS: 'ProfileDocuments',
    PHOTO: 'ProfilePhoto',
    CONFIRMATION: 'ProfileConfirmation',
} as const;
/** @deprecated Use HEALTH_ROUTES */ export const MOBILE_HEALTH_ROUTES = {
    DASHBOARD: 'HealthDashboard',
    METRICS: 'HealthMetrics',
    GOALS: 'HealthGoals',
    DEVICES: 'DeviceConnection',
    HISTORY: 'MedicalHistory',
    ADD_METRIC: 'AddMetric',
    METRIC_DETAIL: 'MetricDetail',
    MEDICATION_LIST: 'HealthMedicationList',
    MEDICATION_ADD: 'HealthMedicationAdd',
    MEDICATION_DETAIL: 'HealthMedicationDetail',
    MEDICATION_SEARCH: 'HealthMedicationSearch',
    MEDICATION_REMINDER: 'HealthMedicationReminder',
    MEDICATION_ALARM: 'HealthMedicationAlarm',
} as const;
/** @deprecated Use CARE_ROUTES */ export const MOBILE_CARE_ROUTES = {
    APPOINTMENTS: 'Appointments',
    BOOK_APPOINTMENT: 'AppointmentBooking',
    TELEMEDICINE: 'Telemedicine',
    SYMPTOM_CHECKER: 'SymptomChecker',
    SYMPTOM_BODY_MAP: 'CareSymptomBodyMap',
    SYMPTOM_DETAIL: 'CareSymptomDetail',
    SYMPTOM_SEVERITY: 'CareSymptomSeverity',
    SYMPTOM_QUESTIONS: 'CareSymptomQuestions',
    SYMPTOM_RESULT: 'CareSymptomResult',
    SYMPTOM_RECOMMENDATION: 'CareSymptomRecommendation',
    MEDICATIONS: 'MedicationTracking',
    TREATMENT_PLANS: 'TreatmentPlan',
    DOCTOR_SEARCH: 'CareDoctorSearch',
    DOCTOR_FILTERS: 'CareDoctorFilters',
    DOCTOR_PROFILE: 'CareDoctorProfile',
    DOCTOR_AVAILABILITY: 'CareDoctorAvailability',
    BOOKING_SCHEDULE: 'CareBookingSchedule',
    BOOKING_CONFIRMATION: 'CareBookingConfirmation',
    WAITING_ROOM: 'CareWaitingRoom',
} as const;
/** @deprecated Use GLOBAL_ROUTES */ export const MOBILE_GLOBAL_ROUTES = {
    NOTIFICATION_DETAIL: 'NotificationDetail',
    SEARCH: 'Search',
    SEARCH_RESULTS: 'SearchResults',
    SETTINGS: 'Settings',
    SETTINGS_EDIT: 'SettingsEdit',
    SETTINGS_NOTIFICATIONS: 'SettingsNotifications',
    SETTINGS_PRIVACY: 'SettingsPrivacy',
} as const;
/** @deprecated Use PLAN_ROUTES */ export const MOBILE_PLAN_ROUTES = {
    DASHBOARD: 'PlanDashboard',
    COVERAGE: 'Coverage',
    DIGITAL_CARD: 'DigitalCard',
    CLAIMS: 'ClaimHistory',
    CLAIM_SUBMISSION: 'ClaimSubmission',
    COST_SIMULATOR: 'CostSimulator',
    BENEFITS: 'Benefits',
} as const;
/** @deprecated Use AUTH_ROUTES */ export const WEB_AUTH_ROUTES = {
    WELCOME: '/auth/welcome',
    ONBOARDING: '/auth/onboarding',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    EMAIL_VERIFY: '/auth/email-verify',
    SET_PASSWORD: '/auth/set-password',
} as const;
/** @deprecated Use PROFILE_ROUTES */ export const WEB_PROFILE_ROUTES = {
    SETUP: '/profile/setup',
    ADDRESS: '/profile/address',
    DOCUMENTS: '/profile/documents',
    PHOTO: '/profile/photo',
    CONFIRMATION: '/profile/confirmation',
} as const;
/** @deprecated Use HEALTH_ROUTES */ export const WEB_HEALTH_ROUTES = {
    DASHBOARD: '/health/dashboard',
    METRICS: '/health/metrics',
    GOALS: '/health/goals',
    DEVICES: '/health/devices',
    HISTORY: '/health/history',
    MEDICATIONS: '/health/medications',
    MEDICATION_ADD: '/health/medications/add',
    MEDICATION_DETAIL: '/health/medications/:id',
    MEDICATION_REMINDER: '/health/medications/reminder',
} as const;
/** @deprecated Use CARE_ROUTES */ export const WEB_CARE_ROUTES = {
    APPOINTMENTS: '/care/appointments',
    BOOK_APPOINTMENT: '/care/appointments/book',
    TELEMEDICINE: '/care/telemedicine',
    SYMPTOM_CHECKER: '/care/symptom-checker',
    SYMPTOM_BODY_MAP: '/care/symptom-checker/body-map',
    SYMPTOM_DETAIL: '/care/symptom-checker/detail',
    SYMPTOM_SEVERITY: '/care/symptom-checker/severity',
    SYMPTOM_QUESTIONS: '/care/symptom-checker/questions',
    SYMPTOM_RESULT: '/care/symptom-checker/result',
    SYMPTOM_RECOMMENDATION: '/care/symptom-checker/recommendation',
    MEDICATIONS: '/care/medications',
    TREATMENT_PLANS: '/care/treatment-plans',
    DOCTOR_SEARCH: '/care/appointments/search',
    DOCTOR_FILTERS: '/care/appointments/filters',
    DOCTOR_PROFILE: '/care/appointments/doctor/:id',
    DOCTOR_AVAILABILITY: '/care/appointments/doctor/availability',
    BOOKING_CONFIRMATION: '/care/appointments/confirm',
    WAITING_ROOM: '/care/appointments/waiting-room',
    DOCTOR_REVIEWS: '/care/appointments/reviews',
    APPOINTMENT_TYPE: '/care/appointments/appointment-type',
    BOOKING_REASON: '/care/appointments/reason-for-visit',
    BOOKING_DOCUMENTS: '/care/appointments/documents',
    BOOKING_INSURANCE: '/care/appointments/insurance',
    BOOKING_SUCCESS: '/care/appointments/success',
    APPOINTMENTS_LIST: '/care/appointments/list',
    APPOINTMENT_RESCHEDULE: '/care/appointments/reschedule',
    APPOINTMENT_CANCEL: '/care/appointments/cancel',
    APPOINTMENT_CANCELLED: '/care/appointments/cancelled',
    APPOINTMENT_NO_SHOW: '/care/appointments/no-show',
    PRE_VISIT_CHECKLIST: '/care/appointments/pre-visit',
    RATE_VISIT: '/care/appointments/rate-visit',
    SAVED_DOCTORS: '/care/appointments/saved-doctors',
} as const;
/** @deprecated Use PLAN_ROUTES */ export const WEB_PLAN_ROUTES = {
    DASHBOARD: '/plan',
    COVERAGE: '/plan/coverage',
    DIGITAL_CARD: '/plan/card',
    CLAIMS: '/plan/claims',
    COST_SIMULATOR: '/plan/simulator',
    BENEFITS: '/plan/benefits',
} as const;
/** @deprecated Use GLOBAL_ROUTES */ export const WEB_GLOBAL_ROUTES = {
    NOTIFICATION_DETAIL: '/notifications/detail',
    SEARCH: '/search',
    SEARCH_RESULTS: '/search/results',
    SETTINGS_EDIT: '/profile/edit',
    SETTINGS_NOTIFICATIONS: '/profile/notifications',
    SETTINGS_PRIVACY: '/profile/privacy',
} as const;

// -- Utility ------------------------------------------------------------------
/**
 * Constructs a web route path by substituting :param placeholders with values.
 * @param route - Route template (e.g., '/care/appointments/doctor/:id')
 * @param params - Key-value pairs to substitute (e.g., { id: '123' })
 * @returns Resolved path (e.g., '/care/appointments/doctor/123')
 */
export const getWebRouteWithParams = (route: string, params: Record<string, string | number>): string => {
    let result = route;
    Object.keys(params).forEach((key) => {
        result = result.replace(`:${key}`, params[key].toString());
    });
    return result;
};
