/**
 * Barrel registry for all Figma PNG illustrations.
 * Auto-generated from asset-index.json -- 141 PNGs across 18 sections.
 */

export const illustrations = {
    achievements: [require('./achievements/achievements-01.png')],
    activity: [
        require('./activity/activity-01.png'),
        require('./activity/activity-02.png'),
        require('./activity/activity-03.png'),
        require('./activity/activity-04.png'),
        require('./activity/activity-05.png'),
        require('./activity/activity-06.png'),
        require('./activity/activity-07.png'),
        require('./activity/activity-08.png'),
        require('./activity/activity-09.png'),
        require('./activity/activity-10.png'),
        require('./activity/activity-11.png'),
        require('./activity/activity-12.png'),
        require('./activity/activity-13.png'),
        require('./activity/activity-14.png'),
        require('./activity/activity-15.png'),
        require('./activity/activity-16.png'),
        require('./activity/activity-17.png'),
        require('./activity/activity-18.png'),
        require('./activity/activity-19.png'),
        require('./activity/activity-20.png'),
        require('./activity/activity-21.png'),
        require('./activity/activity-22.png'),
        require('./activity/activity-23.png'),
        require('./activity/activity-24.png'),
        require('./activity/activity-25.png'),
    ],
    aiCompanion: [require('./ai-companion/ai-companion-01.png')],
    authentication: [require('./authentication/authentication-01.png')],
    community: [
        require('./community/community-01.png'),
        require('./community/community-02.png'),
        require('./community/community-03.png'),
        require('./community/community-04.png'),
        require('./community/community-05.png'),
        require('./community/community-06.png'),
        require('./community/community-07.png'),
        require('./community/community-08.png'),
        require('./community/community-09.png'),
        require('./community/community-10.png'),
        require('./community/community-11.png'),
        require('./community/community-12.png'),
        require('./community/community-13.png'),
        require('./community/community-14.png'),
    ],
    consultation: [require('./consultation/consultation-01.png')],
    cycleTracking: [require('./cycle-tracking/cycle-tracking-01.png')],
    errorUtility: [
        require('./error-utility/error-utility-01.png'),
        require('./error-utility/error-utility-02.png'),
        require('./error-utility/error-utility-03.png'),
        require('./error-utility/error-utility-04.png'),
        require('./error-utility/error-utility-05.png'),
        require('./error-utility/error-utility-06.png'),
        require('./error-utility/error-utility-07.png'),
        require('./error-utility/error-utility-08.png'),
    ],
    healthAssessment: [require('./health-assessment/health-assessment-01.png')],
    medication: [require('./medication/medication-01.png')],
    notifications: [require('./notifications/notifications-01.png')],
    nutrition: [
        require('./nutrition/nutrition-01.png'),
        require('./nutrition/nutrition-02.png'),
        require('./nutrition/nutrition-03.png'),
        require('./nutrition/nutrition-04.png'),
        require('./nutrition/nutrition-05.png'),
        require('./nutrition/nutrition-06.png'),
        require('./nutrition/nutrition-07.png'),
        require('./nutrition/nutrition-08.png'),
        require('./nutrition/nutrition-09.png'),
        require('./nutrition/nutrition-10.png'),
        require('./nutrition/nutrition-11.png'),
        require('./nutrition/nutrition-12.png'),
        require('./nutrition/nutrition-13.png'),
        require('./nutrition/nutrition-14.png'),
        require('./nutrition/nutrition-15.png'),
        require('./nutrition/nutrition-16.png'),
        require('./nutrition/nutrition-17.png'),
        require('./nutrition/nutrition-18.png'),
        require('./nutrition/nutrition-19.png'),
    ],
    profileSetup: [
        require('./profile-setup/profile-setup-01.png'),
        require('./profile-setup/profile-setup-02.png'),
        require('./profile-setup/profile-setup-03.png'),
        require('./profile-setup/profile-setup-04.png'),
        require('./profile-setup/profile-setup-05.png'),
        require('./profile-setup/profile-setup-06.png'),
        require('./profile-setup/profile-setup-07.png'),
        require('./profile-setup/profile-setup-08.png'),
        require('./profile-setup/profile-setup-09.png'),
        require('./profile-setup/profile-setup-10.png'),
        require('./profile-setup/profile-setup-11.png'),
        require('./profile-setup/profile-setup-12.png'),
        require('./profile-setup/profile-setup-13.png'),
        require('./profile-setup/profile-setup-14.png'),
        require('./profile-setup/profile-setup-15.png'),
        require('./profile-setup/profile-setup-16.png'),
        require('./profile-setup/profile-setup-17.png'),
        require('./profile-setup/profile-setup-18.png'),
        require('./profile-setup/profile-setup-19.png'),
        require('./profile-setup/profile-setup-20.png'),
        require('./profile-setup/profile-setup-21.png'),
        require('./profile-setup/profile-setup-22.png'),
        require('./profile-setup/profile-setup-23.png'),
    ],
    sleep: [
        require('./sleep/sleep-01.png'),
        require('./sleep/sleep-02.png'),
        require('./sleep/sleep-03.png'),
        require('./sleep/sleep-04.png'),
        require('./sleep/sleep-05.png'),
        require('./sleep/sleep-06.png'),
        require('./sleep/sleep-07.png'),
        require('./sleep/sleep-08.png'),
        require('./sleep/sleep-09.png'),
        require('./sleep/sleep-10.png'),
        require('./sleep/sleep-11.png'),
        require('./sleep/sleep-12.png'),
        require('./sleep/sleep-13.png'),
        require('./sleep/sleep-14.png'),
        require('./sleep/sleep-15.png'),
        require('./sleep/sleep-16.png'),
        require('./sleep/sleep-17.png'),
        require('./sleep/sleep-18.png'),
        require('./sleep/sleep-19.png'),
        require('./sleep/sleep-20.png'),
        require('./sleep/sleep-21.png'),
        require('./sleep/sleep-22.png'),
        require('./sleep/sleep-23.png'),
        require('./sleep/sleep-24.png'),
        require('./sleep/sleep-25.png'),
        require('./sleep/sleep-26.png'),
        require('./sleep/sleep-27.png'),
    ],
    splash: [
        require('./splash/splash-01.png'),
        require('./splash/splash-02.png'),
        require('./splash/splash-03.png'),
        require('./splash/splash-04.png'),
        require('./splash/splash-05.png'),
    ],
    symptomChecker: [require('./symptom-checker/symptom-checker-01.png')],
    welcome: [require('./welcome/welcome-01.png')],
    wellness: [
        require('./wellness/wellness-01.png'),
        require('./wellness/wellness-02.png'),
        require('./wellness/wellness-03.png'),
        require('./wellness/wellness-04.png'),
        require('./wellness/wellness-05.png'),
        require('./wellness/wellness-06.png'),
        require('./wellness/wellness-07.png'),
        require('./wellness/wellness-08.png'),
        require('./wellness/wellness-09.png'),
        require('./wellness/wellness-10.png'),
    ],
} as const;

export type IllustrationSection = keyof typeof illustrations;
