{
  "name": "austa-superapp",
  "version": "1.0.0",
  "description": "AUSTA SuperApp - A unified digital health platform with journey-centered approach and gamification",
  "private": true,
  "engines": {
    "node": ">=18.0.0",
    "npm": ">=8.0.0"
  },
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "dev": "next dev",
    "build": "next build",
    "build:mobile": "eas build",
    "lint": "eslint .",
    "format": "prettier --write .",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage",
    "test:e2e": "cypress run",
    "test:mobile": "detox test",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build",
    "prepare": "husky install",
    "postinstall": "prisma generate"
  },
  "dependencies": {
    "@apollo/client": "^3.8.0",
    "@expo/vector-icons": "^13.0.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@prisma/client": "^4.16.2",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "apollo-server-express": "^3.12.0",
    "axios": "^1.4.0",
    "date-fns": "^2.30.0",
    "expo": "^49.0.0",
    "expo-localization": "~14.3.0",
    "expo-secure-store": "~12.3.0",
    "expo-status-bar": "~1.6.0",
    "graphql": "^16.7.1",
    "i18next": "^23.2.11",
    "next": "^13.4.12",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.45.2",
    "react-i18next": "^13.0.2",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-web": "~0.19.6",
    "react-query": "^3.39.3",
    "socket.io": "^4.7.1",
    "socket.io-client": "^4.7.1",
    "styled-components": "^6.0.5",
    "victory-native": "^36.6.11",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@babel/core": "^7.22.9",
    "@storybook/addon-actions": "^7.1.0",
    "@storybook/addon-essentials": "^7.1.0",
    "@storybook/addon-interactions": "^7.1.0",
    "@storybook/addon-links": "^7.1.0",
    "@storybook/addon-onboarding": "^1.0.8",
    "@storybook/blocks": "^7.1.0",
    "@storybook/nextjs": "^7.1.0",
    "@storybook/react": "^7.1.0",
    "@storybook/testing-library": "^0.2.0",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^14.0.0",
    "@testing-library/react-native": "^12.1.3",
    "@types/jest": "^29.5.3",
    "@types/node": "^20.4.5",
    "@types/react": "^18.2.17",
    "@types/react-native": "^0.72.2",
    "@typescript-eslint/eslint-plugin": "^6.2.0",
    "@typescript-eslint/parser": "^6.2.0",
    "babel-jest": "^29.6.1",
    "babel-plugin-named-exports-order": "^0.0.2",
    "cypress": "^12.17.2",
    "detox": "^20.11.0",
    "eas-cli": "^3.17.1",
    "eslint": "^8.46.0",
    "eslint-config-next": "^13.4.12",
    "eslint-config-prettier": "^8.9.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-react": "^7.33.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-storybook": "^0.6.13",
    "husky": "^8.0.3",
    "jest": "^29.6.1",
    "jest-expo": "^49.0.0",
    "lint-staged": "^13.2.3",
    "msw": "^1.2.2",
    "prettier": "^3.0.0",
    "prisma": "^4.16.2",
    "storybook": "^7.1.0",
    "ts-jest": "^29.1.1",
    "typescript": "^5.1.6",
    "webpack": "^5.88.2"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "eslint --fix",
      "prettier --write"
    ]
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ],
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx}",
      "!**/node_modules/**",
      "!**/coverage/**",
      "!**/.storybook/**",
      "!**/storybook-static/**"
    ]
  },
  "resolutions": {
    "react-devtools-core": "~4.25.0"
  },
  "overrides": {
    "react-refresh": "~0.14.0"
  }
}