apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: austa-prometheus
  namespace: monitoring
  labels:
    app: austa-prometheus
spec:
  serviceAccountName: austa-prometheus
  version: v2.48.0
  replicas: 2
  ruleSelector:
    matchLabels:
      role: alert-rules
      severity: critical
  probeNamespaceLabel: monitoring
  scrapeInterval: 30s
  evaluationInterval: 30s
  externalLabels:
    cluster: austa-superapp
  resources:
    requests:
      memory: 400Mi
      cpu: 200m
    limits:
      memory: 800Mi
      cpu: 400m
  retention: 7d
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi