module.exports = {
    coverageProvider: 'v8',
    moduleFileExtensions: ['js', 'json', 'ts'],
    rootDir: '.',
    testRegex: '.*\\.spec\\.ts$',
    transform: { '^.+\\.(t|j)s$': ['ts-jest', { diagnostics: false }] },
    collectCoverageFrom: [
        'src/**/*.(t|j)s',
        '!src/**/*.module.ts',
        '!src/**/*.interface.ts',
        '!src/**/*.dto.ts',
    ],
    coverageDirectory: './coverage',
    testEnvironment: 'node',
    moduleNameMapper: {
        '^@app/shared/(.*)$': '<rootDir>/src/$1',
        '^@app/auth/(.*)$': '<rootDir>/../auth-service/src/$1',
        '^@app/health/(.*)$': '<rootDir>/../health-service/src/$1',
        '^@app/care/(.*)$': '<rootDir>/../care-service/src/$1',
        '^@app/plan/(.*)$': '<rootDir>/../plan-service/src/$1',
        '^@app/gamification/(.*)$': '<rootDir>/../gamification-engine/src/$1',
        '^@app/notifications/(.*)$': '<rootDir>/../notification-service/src/$1',
        '^@/(.*)$': '<rootDir>/src/$1',
    },
    testTimeout: 10000,
};
