/**
 * Notification service error codes
 */
export const ERROR_CODES = {
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_001',
  NOTIFICATION_VALIDATION_ERROR: 'NOTIFICATION_002',
  NOTIFICATION_TECHNICAL_ERROR: 'NOTIFICATION_003',
  NOTIFICATION_EXTERNAL_ERROR: 'NOTIFICATION_004',
  NOTIFICATION_BUSINESS_ERROR: 'NOTIFICATION_005',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_001',
  TEMPLATE_VALIDATION_ERROR: 'TEMPLATE_002',
  TEMPLATE_TECHNICAL_ERROR: 'TEMPLATE_003',
  PREFERENCE_NOT_FOUND: 'PREFERENCE_001',
  PREFERENCE_VALIDATION_ERROR: 'PREFERENCE_002',
  PREFERENCE_TECHNICAL_ERROR: 'PREFERENCE_003'
};