nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  "@testing-library/jest-native@*":
    peerDependencies:
      "react-test-renderer": "18.2.0"
  "react-test-renderer@*":
    peerDependencies:
      "react": "18.2.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
# Removed Berry reference to use classic Yarn
# yarnPath: .yarn/releases/yarn-3.5.1.cjs