#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running package.json validation..."
node scripts/validate-package-json.js

# Only run the validation if previous command succeeded
if [ $? -eq 0 ]; then
  echo "🧪 Running linters..."
  npx lint-staged
fi